services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        container_name: laravel_app
        ports:
            - "8000:80"
            - "5173:5173"
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db
        networks:
            - senff

    db:
        image: mysql:8.0
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_INITDB_SKIP_TZINFO: 1
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/conf.d:/etc/mysql/conf.d
        networks:
            - senff

volumes:
    db_data:

networks:
    senff:
        driver: bridge
